spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: user01
    password: 1234
    driver-class-name: oracle.jdbc.OracleDriver
  mvc:
    view: #view 경로 및 확장자 지정
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 1MB #파일 하나 용량
      max-request-size: 10MB #파일이 여러 개면 총 파일 용량
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
mybatis:
  type-aliases-package: ksy.shop.**.vo
  mapper-locations: file:src/main/java/ksy/shop/**/dao/*.xml
logging:
  level:
    '[ksy.shop]': debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace