spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: user01
    password: 1234
    driver-class-name: oracle.jdbc.OracleDriver
  mvc:
    view: #view 경로 및 확장자 지정
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 1MB #파일 하나 용량
      max-request-size: 10MB #파일이 여러 개면 총 파일 용량
  jpa:
    hibernate:
      ddl-auto: none # none -> DB에 이미 테이블이 존재하고 데이터가 존재할 때, validate -> 엔티티 매핑 정보와 실제 DB 테이블 구조를 검증만할 때, update -> 엔티티 매핑 정보에 따라 테이블을 업데이트할 때, create -> 실행 시 기존 테이블을 삭제하고 엔티티 매핑 정보에 따라 새로 생성해야할 때, create-drop -> create와 동일하지만 실행 종료시 테이블 삭제해야할 때
    properties:
      hibernate:
        format_sql: true
    show-sql: true
mybatis:
  type-aliases-package: ksy.shop.**.domain
  mapper-locations: file:src/main/java/ksy/shop/**/dao/*.xml
logging:
  level:
    '[ksy.shop]': debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace